### ISSUE TITLE
[Help] —— Could you please explain the relationship between the custom filter function (the second parameter) in the server/filter file and the paginate method?

### ISSUE THREAD

**Issue by core-admin** [get-convex/convex-helpers#381]
I am developing a feature for fuzzy search using the filter function you provided, and it supports pagination.

Suppose there are 20 entries in my database. When using paginate to query, 10 entries are displayed per page. However, when I filter using a keyword (let's assume there are 5 entries matching the keyword), I notice that the number of results is often much smaller.

Initially, I thought there might be an issue with my code logic. After checking the logs, it seems that pagination is executed first, and then each entry is passed into the filter callback function for comparison (I'm not sure if my understanding is correct). For example, if 3 out of these 10 entries match the criteria, and the other 2 matching entries happen to be on the next page, I end up with only 3 results when searching. I have to load the next page to get the remaining 2, even though the 5 matching entries do not exceed the pagination limit of 10. I would like all 5 entries to be retrieved at once unless the number of matches exceeds the pagination limit.

Here is my code:

```typescript
export const get = query({
  args: v.object({
    paginationOpts: paginationOptsValidator,
    search: v.optional(v.string()),
  }),
  handler: async (ctx, { search, paginationOpts }) => {
    const user = await ctx.auth.getUserIdentity();
    if (!user) {
      throw new ConvexError('Unauthorized');
    }

    if (search) {
      return await filter(
        ctx.db.query('documents').withIndex('by_owner_id', q => {
          return q.eq('ownerId', user.subject);
        }),
        document => {
          return document.title.includes(search);
        },
      )
        .order('desc')
        .paginate(paginationOpts);
    }

    return await ctx.db
      .query('documents')
      .withIndex('by_owner_id', q => {
        return q.eq('ownerId', user.subject);
      })
      .order('desc')
      .paginate(paginationOpts);
  },
});
```

I'm a front-end developer and not very skilled with databases. I wanted to confirm with you whether this design was intentional. If this is the intended behavior, what would be the best way for me to achieve my needs? Thank you very much.

---

Chinese：

我正在使用您提供的 filter 函数进行模糊查询的功能开发，并且支持分页。

假设我的数据库中存在20条数据，使用paginate查询时，每页展示10条数据，当我通过关键字进行过滤时（假设当前符合关键字的数据有5条），发现查询出来的数据总是会少很多。

刚开始我认为是我编写的代码逻辑有问题，我通过检查日志发现，其底层好像是先执行了分页，然后在将每一条数据传入filter的回调函数进行比对（不知道我理解的对不对），比如，这10条数据中有3条符合条件，符合条件的另外2条数据刚好在下一页中，就会出现我在搜索时，只能查询出来3条，另外两条查询不出来，我必须继续加载下一页数据才行，但其实这5条数据没有大于分页要求的10条，我希望它们能一次性全部查询出来，除非匹配的数据大于分页要求的条数。

**Comment by ianmacartney** [comment]
Yes the filter is applied after pagination. If your goal is to show items
to users 10 at a time on the client, my suggestion would be:
1. Increase the pagination fetch size to 20.
2. Use the usePaginatedQuery hook, and if you have <10 items, call
`loadMore`.
3. Show the items on `pageNum` using the `results.slice(pageNum * 10,
(pageNum+1) * 10)` or have an infinite-scroll UI where you loadMore
whenever the user gets to the bottom of the list, if the status is
CanLoadMore

https://stack.convex.dev/complex-filters-in-convex#escape-hatch-pagination

This limitation helps avoiding fetching too much data in one query, since
if no rows match you'd end up scanning your whole database table, which
would break if there were too many rows to read in one query.

**Comment by core-admin** [comment]
I see, thanks for answering my questions.
